#pragma once

#include "ModbusSDevice/log_base.h"

typedef enum
{
   MODBUS_RTU_SDEVICE_STATUS_OK                        = MODBUS_SDEVICE_STATUS_OK,
   MODBUS_RTU_SDEVICE_STATUS_CORRUPTED_REQUEST         = MODBUS_SDEVICE_STATUS_CORRUPTED_REQUEST,
   MODBUS_RTU_SDEVICE_STATUS_WRONG_FUNCTION_CODE       = MODBUS_SDEVICE_STATUS_WRONG_FUNCTION_CODE,
   MODBUS_RTU_SDEVICE_STATUS_REGISTERS_ACCESS_FAIL     = MODBUS_SDEVICE_STATUS_REGISTERS_ACCESS_FAIL,

   MODBUS_RTU_SDEVICE_STATUS_SLAVE_ADDRESS_SET_INVALID
} ModbusRtuSDeviceStatus;
