#pragma once

#include "SDeviceCore/core.h"

#if (SDEVICE_CORE_VERSION_MAJOR != 8) || (SDEVICE_CORE_VERSION_MINOR < 0)
#error SDevice core version is incorrect.
#endif

#ifdef MODBUS_SDEVICE_USE_EXTERNAL_CONFIG
#include "modbus_sdevice_config.h"
#endif

#if defined DOXYGEN
#define MODBUS_RTU_SDEVICE_USE_INTERNAL_CRC
#undef MODBUS_RTU_SDEVICE_USE_EXTERNAL_CRC
#endif

#if !defined MODBUS_RTU_SDEVICE_STATIC_INTERNAL_HANDLE_CONTEXT || defined DOXYGEN
#define MODBUS_RTU_SDEVICE_STATIC_INTERNAL_HANDLE_CONTEXT NULL
#endif

#if !defined MODBUS_RTU_SDEVICE_STATIC_INTERNAL_HANDLE_IDENTIFIER || defined DOXYGEN
#define MODBUS_RTU_SDEVICE_STATIC_INTERNAL_HANDLE_IDENTIFIER ((SDeviceHandleIdentifier)0)
#endif

#if !defined MODBUS_RTU_SDEVICE_INTERNAL_CRC16_HANDLE_IDENTIFIER || defined DOXYGEN
#define MODBUS_RTU_SDEVICE_INTERNAL_CRC16_HANDLE_IDENTIFIER ((SDeviceHandleIdentifier)0)
#endif

#if !defined MODBUS_UDP_SDEVICE_BTU_ADDRESS_SIZE || defined DOXYGEN
#define MODBUS_UDP_SDEVICE_BTU_ADDRESS_SIZE 6U
#endif
