#pragma once

typedef enum
{
   MODBUS_SDEVICE_STATUS_OK,
   MODBUS_SDEVICE_STATUS_CORRUPTED_REQUEST,
   MODBUS_SDEVICE_STATUS_WRONG_FUNCTION_CODE,
   MODBUS_SDEVICE_STATUS_REGISTERS_ACCESS_FAIL
} ModbusSDeviceStatus;
