#pragma once

#include "ModbusSDevice/public_tcp.h"

SDEVICE_RUNTIME_DATA_FORWARD_DECLARATION(ModbusTcp);

SDEVICE_RUNTIME_DATA_DECLARATION(ModbusTcp)
{
   uint8_t MbapHeaderBuffer[MODBUS_TCP_SDEVICE_MBAP_HEADER_SIZE];
};

SDEVICE_HANDLE_DECLARATION(ModbusTcp);
