#pragma once

#include "internal_base.h"

SDEVICE_RUNTIME_DATA_FORWARD_DECLARATION(Modbus);

SDEVICE_RUNTIME_DATA_DECLARATION(Modbus)
{

};

SDEVICE_HANDLE_DECLARATION(Modbus);
SDEVICE_INTERNAL_ALIASES_DECLARATION(Modbus);
